const TYPES = {
  UPDATE_FORM: 'UPDATE_FORM',
  CLEAR_FORM: 'CLEAR_FORM',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  SET_JOBS: 'SET_JOBS',
  SET_VIEW: 'SET_VIEW',
  CLEAR_VIEW: 'CLEAR_VIEW',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  SET_JOB: 'SET_JOB',
  SET_INBOX: 'SET_INBOX',
  SET_MESSAGES: 'SET_MESSAGES',
  SET_CHATROOM: 'SET_CHATROOM',
  UPLOAD_PHOTO: 'UPLOAD_PHOTO',
  UPDATE_ACCOUNT_FAIL: 'UPDATE_ACCOUNT_FAIL',
  SET_ALERTS: 'SET_ALERTS',
  SET_NEW_ALERTS: 'SET_NEW_ALERTS',
  SET_STRIPE_ACCOUNT: 'SET_STRIPE_ACCOUNT',
};

export default TYPES;
