const TYPES = {
  UPDATE_FORM: 'UPDATE_FORM',
  CLEAR_FORM: 'CLEAR_FORM',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  SET_JOBS: 'SET_JOBS',
  SET_VIEW: 'SET_VIEW',
  CLEAR_VIEW: 'CLEAR_VIEW',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  FILTER_JOBS: 'FILTER_JOBS',
  SET_JOB_FILTER: 'SET_JOB_FILTER',
  CLEAR_JOB_FILTER: 'CLEAR_JOB_FILTER',
};

export default TYPES;
